import cv2
img=cv2.imread('text.jpg')
cv2.imshow('img',img)
img1=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow('img1',img1)
img2=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
cv2.imshow("img2",img2)
img3=cv2.resize(img,(600,500))
cv2.imshow('img3',img3)
print(img.shape)
print(img.size)
print(img3.size)
print(img3.shape)
ret,thresh=cv2.threshold(img1,150,255,cv2.THRESH_OTSU)
cv2.imshow('thresh',thresh)
adaptive_thresh=cv2.adaptiveThreshold(img1,255,cv2.ADAPTIVE_THRESH_MEAN_C,cv2.THRESH_BINARY,5,15)
adaptive_thresh1=cv2.adaptiveThreshold(img1,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,5,15)
adaptive_thresh2=cv2.adaptiveThreshold(img1,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY_INV,5,15)
cv2.imshow('thresh',adaptive_thresh)
cv2.imshow('thresh1',adaptive_thresh1)
cv2.imshow('thresh2',adaptive_thresh2)
cv2.imwrite('grey.jpg',img1)
cv2.imwrite('D:/ip_task/hsv.jpg',img2)
cv2.imwrite('D:/ip_task/ad1.jpg',thresh)
cv2.imwrite('D:/ip_task/ad2.jpg',adaptive_thresh)
cv2.imwrite('D:/ip_task/ad3.jpg',adaptive_thresh1)
cv2.imwrite('D:/ip_task/ad4.jpg',adaptive_thresh2)



cv2.waitKey(0)
cv2.destroyAllWindows()